Repository february-labs/devgpt-releases, pull requests merged in 2023-09, with the labels that each got.

#74 Scroll new messages into view
  renderer/src/components/global/displays/MessagesDisplay.tsx
Labels: Bug

#75 Fix broken keyboard shortcut to open target repo
  renderer/src/components/global/sidebar/elements/MenuTabs.tsx
Labels: Bug, Compatability

#72 Update README.md with correct filename for supabase sql set-up
  supabase/SupabaseSetup.sql
Labels: Documentation, Improvement

#78 Hotfix z index issue for sync / copy / upvote / downvote bar
  renderer/src/components/global/displays/CodeDisplay.tsx
Labels: Bug

#104 Update Linux installation file format in README.md
  README.md
Labels: Documentation
